sudo: required
language: scala
scala:
- 2.11.6
services:
- docker
install: true
before_install:
- openssl aes-256-cbc -K $encrypted_cb4cdd7947fc_key -iv $encrypted_cb4cdd7947fc_iv
  -in tests/credentials.json.enc -out tests/credentials.json -d
- "./tools/travis/setup.sh"
script:
- "./tools/travis/build.sh"
