sudo: required
language: scala
scala:
- 2.11.6
services:
- docker
install: true
before_install:
- openssl aes-256-cbc -K $encrypted_7bdf8d41d192_key -iv $encrypted_7bdf8d41d192_iv
  -in credentials.json.enc -out credentials.json -d
- "./tools/travis/setup.sh"
script:
- "./tools/travis/build.sh"
