# A Travis CI configuration file.

sudo: required

language: scala

services:
  - docker

install: true

before_install:
  - ./tools/travis/setup.sh

script:
  - ./tools/travis/build.sh

notifications:
  email: false
  webhooks:
    urls:
      secure: "iNZ/jwtBbL3nFqV03YsuPlERcUO/rXGipAkSiSUXIU1kN/czT900ahKHC5Y1rKW/Ix2dWXr9me59vQlXlf7uquSSGVjoC8BU4yjth6uKnWZ/TLpWSpOvQYo915bjd7ZGRuwomGv7WiXIMK4jlOQv6oCOqAD7ubCpTDyioMimTWAo3vhe1V7BgbV8VqmeHXntEIdAm0CqOg2bDvKoe8z8sYwlfTVlN7nSp30SKtyoiBocjD9FOl4QnDGi1HznvmQar79EJRWJGAj6Cc8oFuqo5ijzrTbFOLGX7ZzPs7BPAip88N87ZbllE7cgbRpei107FDdr061h1T6VSaOhNKN5wArxi4nzQSsCCjDDZ0oqygY2Iejxg1npcB/+5AIvHFG1Iu5AFQlY5+NbuHUQ4DscdRocJVM0nq4FibXXE6lL42qHyRc2v36VukTRM6ypLzn7PsgWy2GEcNvby2yDB0UC4bjKK/f3/O1BGg4o7YYd+QKNJ0AHdD/ElXJqmelppMINKsIsiOAmkuzeXj4fqV9oDjCEUg7A6V+h3MWcH9/b/ud2I+0cybMqPDNeJkcZ44J9rU9aEx/QR/kb7GQJ6miUnB4zOz1fID7YIwegvbKV8o8VKQf0517qxhmScxgBm3UC54Idm1KZhBX4kEXpxJ/hdEpqVGsXi8BvTZkisL//+Pw="
